name: Question Template
description: Template for asking questions

# Define the issue labels for categorization
labels:
  - question

# Define the fields for the issue form
title:
  name: Title
  description: Please provide a brief summary of the question.
  type: text

description:
  name: Description
  description: Please provide a detailed description of the question.
  type: textarea

context:
  name: Context
  description: Please provide any relevant background information or context.
  type: textarea

expected_response:
  name: Expected Response
  description: What kind of response are you expecting?
  type: select
  options:
    - Explanation
    - Code example
    - Suggestion
    - Other

urgency:
  name: Urgency
  description: How urgent is your question?
  type: select
  options:
    - Low
    - Medium
    - High