name: Documentation Suggestions
description: Report an issue or suggest an improvement for our documentation.
body:
  - type: markdown
    attributes:
      value: |
        ## 🛑 This issue belongs in the documentation repository!
        
        To keep our projects organized, we track all documentation-related issues in the dedicated `midnight-docs` repository.
        
        Please open your issue there:
        
        ### **[➡️ Click here to open a new documentation issue](https://github.com/midnightntwrk/midnight-docs/issues/new/choose)**
        
        ---
        *Thank you for helping us improve our docs! You can safely close this tab.*
